### ISSUE TITLE
Visitors should see top of page not bottom

### ISSUE THREAD

**Issue by ericjmorey** [realpython/python-guide#1008] opened 2019-08-26 17:54 UTC
When using Firefox Mobile Browser and Firefox Focus Browser, and Chome Mobile Browser on Android 8.1.0, page visitors to https://docs.python-guide.org/ are shown the bottom of the page being viewed and must scroll to the top to read as one would normally.

Not sure what is causing the jump to the bottom of the pages but it seems pervasive throughout the site.

**Comment by heyhimansh** [comment] 2021-03-27 18:13
you need to add this add the top.

**Comment by dbader** [comment] 2021-04-08 20:10
Thanks for the heads up! I believe this might've been caused by the footer ad banner. I can't reproduce this right now on my end, but let me know if it happens again. Closing this for now :)

**Closed by dbader** 2021-04-08 20:10 UTC
