### ISSUE TITLE
Cebuano Localization

### ISSUE THREAD

**Issue by josephace135** [realpython/python-guide#883] opened 2018-02-23 08:29 UTC
Hi,

Good Day! I would like to contribute on your project thru localizing the docs to my native language. Only if you allow me to do so.

Thank you.

Best Regards,

josephace135 | Joseph Ace Tigas

**Comment by bzaczynski** [comment] 2020-09-14 11:53
Looks like a duplicate of a closed issue: https://github.com/realpython/python-guide/issues/892

**Closed by bzaczynski** 2020-09-14 11:53 UTC
